/* Load default search criteria */

set define off;
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('MEDICAL_CHART_NUMBER', 'MEDICAL_?CHART', 'Medical Chart', 'Health Data', 'N');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('NEXT_OF_KIN', 'NEXT.*KIN', 'Next.*(of)?.*Kin|\bNOK\b', 'Health Data', 'N');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('JOB_TITLE', '(^JOB.*(TITLE|PROFILE|POSITION|RANK|LEVEL)$)|^POSITION|CURR.*JOB|JOB.*CURR|JB.*TITLE', 'Job (Title|Profile|Position|Rank|Level)|Current Job', 'Job Data', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('INCOME', '= SALARY|INCOME|WAGE|REMUNERATION|^SAL$|COMPENSATION|COMP_?RATE|ANNUAL_?RT', 'Salary|Income|Wage|Remuneration|Compensation|Annual Rate', 'Job Data', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('VARIABLE_INCOME', 'BONUS|REWARD|^COMP$|COMMISSION|^COMM$|^VARIABLE$|COMP_SUMMARY|TIPS$', 'Bonus|Reward|Commission|Variable|Tips', 'Job Data', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('STOCK', '^(?!.*(PROD|WH|SUP|MAX|MIN|IN)).*STOCK$|ST.*AWARD|SHARES.*GRANTED', '^(?!.*(Prod|Wh|Sup|Max|Min|In)).*Stock|\bRSU\b|Restricted Stock Unit|Shares', 'Job Data', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('HIRE_DATE', '((ADMISSION|HIRE).*(DATE|DT))|(DT|DATE).*HIRE', '(Admission|Hire).*date', 'Job Data', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('TERMINATION_DATE', 'TERM.*(DATE|DT)|(DATE|DT).*TERM', 'Term.*Date|Date.*Term', 'Job Data', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('FULL_NAME', '^(PERSON|FULL).*NAME$', '(Full|Person).*Name', 'PII', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('FIRST_NAME', '(^FNAME$)|((FIRST|GIVEN).*NAME$)', '(First|Given|Cust).*Name', 'PII', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('LAST_NAME', '(^LNAME$)|((LAST|FAMILY|SUR|PATERNAL).*NAME$)', '(Last|Family|Sur|Paternal).*Name', 'PII', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('SOCIAL_SECURITY_NUMBER', 'SOC.*SEC|^SSN$|SSID', 'Social Security Number', 'PII - IDs', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('MOTHERS_NAME', '^(MOTHER.*NAME|NAME.*MOTHER)$', 'Mother.*Name|Name.*Mother', 'PII', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('FATHERS_NAME', '^(FATHER.*NAME|NAME.*FATHER)$', 'Father.*Name|Name.*Father', 'PII', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('MAIDEN_NAME', '^MAIDEN.*NAME$', 'Maiden Name', 'PII', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('MOTHERS_MAIDEN_NAME', 'MMN| ^MOTHERS?_?MAIDEN', 'Mother''?s maiden', 'PII', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('STREET', 'STREET|^ST$|AVENUE|ROAD|ALLEY|BOULEVARD|PARKWAY|PLAZA|POINT|VALLEY', 'Street.*(Address)?', 'PII - Address', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('CITY', '^CITY$', 'City', 'PII - Address', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('POSTAL_CODE', '^ZIP|POST.*CODE', '^Zip|Post.*Code', 'PII - Address', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('MAIL_STOP', '^MAIL.*STOP$', 'Mail Stop', 'PII - Address', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('STATE', '^STATE$|^ST$', 'State', 'PII - Address', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('COUNTY', 'COUNTY', 'County', 'PII - Address', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('COUNTRY', 'COUNTRY', 'Country', 'PII - Address', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('FULL_ADDRESS', '^(?!IP|MAC|EMAIL).*ADDRESS$|^ADDRESS$', '^(?!IP|MAC|EMAIL).*ADDRESS$', 'PII - Address', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('EMAIL', 'EMAIL|MAIL', 'EMAIL|MAIL', 'PII', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('PHONE', 'PHONE|^TEL|^CELL|MOBILE|((WORK|OFFICE|CONTACT).*(NUM|NO|NBR))', 'Phone|Telephone|Cellphone|Mobile N|Work N|Office N|Contact N', 'PII', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('FINGERPRINT', 'FINGER.*PRINT', 'Finger.*print', 'PII', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('PHOTO', '^(?!.*(PRODUCT|PRDT?)).*(PHOTO)', '^(?!.*(Product|Prdt?)).*(Photo)', 'PII', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('NATIONAL_IDENTIFIER', 'NATIONAL.*ID', 'National.*Id', 'PII - IDs', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('NATIONAL_INSURANCE_NUMBER', 'NATIONAL.*INS|^NI.*NO', 'National.*Ins|\bNINO\b', 'PII - IDs', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('SOCIAL_INSURANCE_NUMBER', 'SOC.*INS|^SIN$', 'Social Insurance Number', 'PII - IDs', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('UNIQUE_POPULATION_REGISTRY_CD', 'UNIQUE.*POPULATION.*CODE|CURP|PERSONAL.*CODE|MEXICO.*CODE', 'Unique Population Registry Code|CURP', 'PII - IDs', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('WORK_PERMIT', '^WORK_?PER', 'Work Permit', 'PII - IDs', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('DRIVERS_LICENSE_NUMBER', '(DL.*NUM)|(DRIV.*(LIC|NUM|ID|NO|NBR))', 'Driv.*Lic', 'PII - IDs', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('PASSPORT_NUMBER', '^PASSPORT.*(NUM|NO|NBR)|^PASSPORT$', 'Passport', 'PII - IDs', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('VISA_NUMBER', '^VISA|^CONTROL_?N|^CASE_?N', 'Visa Number|Control Number|Case Number', 'PII - IDs', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('TAX_IDENTIFICATION_NUMBER', 'TAX.*(ID|NO|NUM|NBR)|^TIN$|^ITIN$|^ATIN$|^EIN$|^PTIN$', 'Tax(payer)? Id', 'PII - IDs', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('NATIONAL_TAXPAYER_IDENTIFIER', 'NATIONAL_?TAX(PAYER)?', 'National Taxpayer', 'PII - IDs', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('VOTER_IDENTIFICATION_NUMBER', '(ELECTORAL|VOTER).*(ID|NO|NUM|NBR)', '(Electoral|Voter).*(ID|No|Num|Nbr)', 'PII - IDs', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('EMP_ID', '^EMP.*(ID|NO|NUM|NBR)', 'Employee (ID|NO|NUM|NBR)', 'Job Data', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('STUDENT_IDENTIFICATION_NUMBER', '^STUD.*(ID|NO|NUM|NBR)', 'Student.*(ID|No|Num|Nbr)', 'PII - IDs', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('USERID', '^HANDLE|^USER|^HASHTAG$|^LOGIN|USER_?NAME|SCREEN_?NAME', 'HANDLE|USER|HASHTAG|LOGIN|USER_?NAME|SCREEN_?NAME|Twitter|Tweet', 'PII - IT Data', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('PASSWORD', '^PWD$|PSWD|PASSW(OR)?D|^CREDENTIAL$|^REG.*PASS$|^REG.*PWD$|^OLD_?PWD$|^OLD_?PASS$|^NEW_?PWD$|^NEW_?PASS$', 'PWD|PSWD|Passw(or)?d|Credential', 'PII - IT Data', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('IP_ADDRESS', '^IP$|_IP_?ADD', 'IP.*ADD', 'PII - IT Data', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('MAC_ADDRESS', '^MAC$|MAC_?ADD', 'MAC.*ADD', 'PII - IT Data', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('COOKIE', 'COOKIE', 'Cookie', 'PII - IT Data', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('LOCATION', '^LOCATION|GPS|^SDO|^ST_GEOM|^XY|^COORD|DATUM$', 'Location|GPS|Spatial|Geom|XY|Coord|Geo.*Spatial', 'PII - IT Data', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('IMEI', '^IMEI|MOBILE.*ID', 'IMEI', 'PII - IT Data', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('GENDER', '^SEX|_SEX$|^GENDER', 'Sex|Gender', 'PII-Linked', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('AGE', '^AGE$', '\bAge\b', 'PII-Linked', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('BIRTHDATE', 'DOB|BIRTH.*DATE|DATE.*BIRTH', '\bDOB\b|Birth.*Date|Date.*Birth', 'PII-Linked - Birth Details', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('BIRTHPLACE', 'BIRTH.*PLACE|PLACE.*BIRTH', 'Birth.*place|Place.*birth', 'PII-Linked - Birth Details', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('NATIONALITY', 'NATIONALITY|HOME.*COUNTRY|^ORIGIN$', 'Nationality|Home.*Country|\bOrigin\b', 'PII-Linked', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('COUNTRY_OF_CITIZENSHIP', '^CITIZENSHIP|COUNTRY.*CITIZENSHIP', 'Citizenship|Country.Citizenship', 'PII-Linked', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('RACE', '^RACE|ETHNICITY', 'Race|Ethnicity', 'PII-Linked', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('RELIGION', 'RELIGION|CHURCH', 'Religion|Church', 'PII-Linked', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('MARITAL_STATUS', 'MARRIED|MARITAL.*STATUS', 'Married|Marital status', 'PII-Linked', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('POLITICAL_PARTY', '^POLITIC(AL)?', 'Political Party|Political Opinion', 'PII-Linked', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('TRADE_UNION_MEMBERSHIP', 'TRADE.*UNION|UNION.*NAME', 'Trade.*Union|Union.*Name', 'PII-Linked', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('SEXUAL_PREFERENCE', '^SEX_?PREF|SEX_?P', 'Sexual Pref', 'PII-Linked', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('CRIMINAL', '^CRIMINAL|^CRIME|^CONVICTED$|DRUG_TEST', 'Criminal|Crime|Convicted|Drug Test', 'PII-Linked', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('CREDIT_CARD_NUMBER', '^(?!.*(DATE|DT|ISSUE)).*(CREDIT|DEBIT).*CARD|^PAN$|PAYMENT_ACCT|^CCN?$|CC_CARD|CCI_N', '(Credit|Debit|Payment) Card', 'Financial Data - PCI', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('CARD_SECURITY_PIN', 'PIN$', '\bPIN\b', 'Financial Data - PCI', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('CARD_SECURITY_CODE', 'SEC.*CODE|CC.*CODE', 'Security Code', 'Financial Data - PCI', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('CARD_EXPIRATION_DATE', 'EXP.*DATE|DATE.*EXP', 'Exp.*Data|Date.*Exp', 'Financial Data - PCI', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('BANK_ACCOUNT_NUMBER', 'BANK.*ACC|CHECKING|SAVINGS', 'Bank Account|Checking|Savings', 'Financial Data - Banking', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('BANK_ROUTING_NUMBER', '(ROUTING|TRANSIT).*(NO|NUM|NBR)', 'Bank Routing|(Routing|Transit) Number', 'Financial Data - Banking', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('IBAN', 'IBAN', 'IBAN', 'Financial Data - Banking', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('BANK_NAME', '^BANK', 'Bank Name', 'Financial Data - Banking', 'Y');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('HEIGHT', '^(?!HTML|BITMAP|APPLET|CHART|ICON|IMAGE|IMG|SCREEN|DIALOG|DISPLAY|PAGE|UNIT|HEADER|FOOTER|CEILING|WINDOW|MIN_SIZE'||CHR(13)||CHR(10)||'|MAX_SIZE|THUMBNAIL).*HEIGHT$|^HEIGHT$|^HT$', '^(?!HTML|BITMAP|APPLET|CHART|ICON|IMAGE|IMG|SCREEN|DIALOG|DISPLAY|PAGE|UNIT|HEADER|FOOTER|CEILING|WINDOW|MIN_S'||CHR(13)||CHR(10)||'IZE|MAX_SIZE|THUMBNAIL).*Height', 'Health Data', 'N');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('WEIGHT', '(PATIENT_?|PERSON_?).*WEIGHT|^WEIGHT$|^WT$', '(PATIENT_?|PERSON_?).*WEIGHT', 'Health Data', 'N');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('HEALTH_INSURANCE_NUMBER', '((INSURANCE|PATIENT).*(NO|NUM|ID|NBR))|PAYER', 'Health Insurance N', 'Health Data', 'N');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('MEDICAL_INFORMATION', 'MEDICAL.*(INFO|DETAILS|CONDITION)', 'Medical (Info|Detail|Cond)', 'Health Data', 'N');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('DISABILITY', 'DISABILITY|HANDICAP|PROF_DISEASE|CHALLENGED', 'Disability|Handicap|Professional Disease|Challenged', 'Health Data', 'N');
Insert into PII_SENSITIVE_TYPES
   (SENSITIVE_TYPE_NAME, COL_NAME_PATTERN, COL_COMMENT_PATTERN, SENSITIVE_CATEGORY, ENFORCED)
 Values
   ('GENETIC', '^RNA$|^DNA$|GENETIC', 'Genetic|\bDNA\b|\bRNA\b|Ribonucleic|Deoxyribonucleic', 'Health Data', 'N');
COMMIT;
